### ISSUE TITLE
Support for file attachments

### ISSUE THREAD

**Issue by nmors** [andrewtelnov/surveyjs#10]
Please add support for the file attachment capability during a survey.

I think, that upon attaching a file, it will encode as a Base64 string. The string would then be returned in the result object

Thanks

**Comment by nmors** [comment]
By the way, if you agree on the feature, I am happy to make a pull request for this !

**Comment by andrewtelnov** [comment]
Hi,
I do not mind to add the feature or accept your pull request, but could you please describe your scenario? 
At the current moment, I do not see how other people may benefit from this functionality. Very likely I'm missing something.
Another question, where do you want to save the attached file?
And is it possible to use questionhtml? You may put any html/script in its html property: http://surveyjs.org/examples/questiontype-html.html.

Thank you,
Andrew

**Comment by nmors** [comment]
The attached file would simply be another field. Because the file will get encoded in base64, it will be safe to put the file inside JSON response at the end of the survey. (E.g. Question : upload file, answer = encoded file)

A use case would be, for example, page 2, "attach supporting documents" or "attach resume", upload photo, "attach pdf report", etc. 

It would need a new question type of "attachment" or "file". Which can accept any format. There should be a custom set filesize limit also.

I can think of this being very handy for many different scenarios

**Comment by andrewtelnov** [comment]
I don't know...
If I would create a UI to post a photo or even a document (pdf/doc), I would have a preview (photo/document) in my UI. The user should see what he/she has just uploaded. Users will expect it, IMHO. 
It means that I would have to store the data somewhere on the server - have a picture preview.

Additionally, having document/picture in JSON... I don't know. I would like to have it in separate file (data blob). It would be more natural.
Of course, it is all doable.

**Comment by nmors** [comment]
I'm not sure I understand why you would want to upload it to a server to show a preview.. This all is entirely possible to do client-side:

Upload element is simple:

```html
<input id="browse" type="file" onchange="previewFiles()" multiple>
```

preview link could be something like: 

```js
window.open("data:application/octet-stream;base64," + base64);
```

or using the example:

https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL

makes it quite a simple implementation!

The only pitfall is that it requires IE 10+, so users with IE 9 and earlier would not work for. There is other approaches that are more compatible with older browsers though.

What do you think?

**Comment by andrewtelnov** [comment]
Hm... You are probably right. I have not investigate this in depth.
Anyway, I would like to store the data, at least optionally, in a separate storage.

**Comment by nmors** [comment]
I have other things on my plate, so haven't been able to start on this yet.

I'll keep this in mind when creating the PR, that you want to be able to store in a separate storage. Normally when I send binary from Client -> server and vice-versa, I do it in Base64 encoded string. 

Just to confirm, you want the option to send it to the server as a ```"application/octet-stream"``` instead of Base64 string inside of ```"application/json"``` ? And to a configurable endpoint? (like `/api/upload`) I'm not sure exactly what you have in mind, but if you were to do this, then the endpoint should at least return an ID for the uploaded file, and that ID would be included in the survey response maybe?

Please correct me If my understanding is wrong

**Comment by andrewtelnov** [comment]
Hello Nathan,
I think, there is should be an event and some properties, where a developer may setup any configuration he may need.
Do you have any deadline? I will not be able to work a lot on SurveyJS this week. I have to do some other stuff as well.
I can create a separate branch: file-attachments, on the next week. I can prove all your pull requests to this branch and provide some input.
What do you think?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
FYI: I am going to work on this feature this week.

**Comment by nmors** [comment]
Great!

Thanks Andrew

**Comment by andrewtelnov** [comment]
Hi,
I have just committed the initial version of 'file' question. There are still a lot of work with service (upload,send/get notification about finishing. and show files/images). As well as I do not introduce the event on survey level yet, but you may build the library from sources and give a try.
Here is the example of JSON for this question:
``
{ type: "file", name: "myimage", storeDataAsText: true, showPreview: true, imageWidth: 150, maxSize: 100000 },
``
Please take into the account, storeDataAsText (store the binary as Base64string in JSON) and showPreview are false by default.
If you do not like something or need more functionality, let me know.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
It is here: http://surveyjs.org/examples/questiontype-file.html

**Comment by noorball** [comment]
Hello,
If attachment control is added to the survey I can attach files in text form.
Could anybody provide information on how to make available file attachment download on survey view and edit?
