### ISSUE TITLE
visibleIf for checkbox questions

### ISSUE THREAD

**Issue by samuliasmala** [andrewtelnov/surveyjs#100]
Hi,
Is it possible to somehow use contain-function for checkbox questions? I would like to show a question is one of the checkboxes is selected regardless of the other checkboxes.

For example, is it possible to modify the attached survey to show the age question for child number 1 regardless if other childs are selected?
[example.txt](https://github.com/andrewtelnov/surveyjs/files/559274/example.txt)

Thanks!

Samuli

**Comment by andrewtelnov** [comment]
Hi @samuliasmala,
I have just checked: `visibleIf: "{haveKids}='Yes' and {kids} contains 3"` works just fine.

Thank you,
Andrew

**Comment by samuliasmala** [comment]
A bit embarrassing since I tried that but I had the 's' missing from contains... Big thanks for quick answer!

Best,
Samuli
