### ISSUE TITLE
onValueChanged event doesn't work for RadioButton and Checkbox after changing template

### ISSUE THREAD

**Issue by Aleyasen** [andrewtelnov/surveyjs#105]
I used the following templates from examples on the website for radio button and checkbox:
```
new Survey.SurveyTemplateText().replaceText('<div class="btn-group" data-toggle="buttons"><!-- ko foreach: { data: question.visibleChoices, as: "item", afterRender: question.koAfterRender}  --> <label class="btn btn-default" data-bind="css:{active: $data.value == question.koValue()}, style:{width: question.koWidth}">   <input type="radio" data-bind="attr: {name: question.name, value: item.value}, checked: question.koValue" /> <span data-bind="text: item.text"></span></label><!-- /ko --><div data-bind="visible:question.hasOther"><div data-bind="template: { name: \'survey-comment\', data: {\'question\': question, \'visible\': question.koOtherVisible } }"></div></div></div>', "question", "radiogroup");
new Survey.SurveyTemplateText().replaceText('<div class="btn-group" data-toggle="buttons"><!-- ko foreach: { data: question.visibleChoices, as: "item", afterRender: question.koAfterRender}  --> <label class="btn btn-default" data-bind="css:{active: question.koValue().indexOf($data.value) > -1}, style:{width: question.koWidth}">   <input type="checkbox" data-bind="attr: {name: question.name, value: item.value}, checked: question.koValue" /> <span data-bind="text: item.text"></span></label><!-- /ko --><div data-bind="visible:question.hasOther"><div data-bind="template: { name: \'survey-comment\', data: {\'question\': question, \'visible\': question.koOtherVisible } }"></div></div></div>', "question", "checkbox");
```
Ref: http://surveyjs.org/examples/survey-customtemplate.html

But now onValueChanged doesn't work anymore for radio buttons and checkboxes. 
```js
 survey.onValueChanged.add(function (sender, options) {
        console.log("Value Changed");
});
```
Ref: http://surveyjs.org/examples/survey-data.html

**Comment by Aleyasen** [comment]
In addition, when I changed the template, the values for buttons and checkboxes are not in the result json (only the textbox values are there)!! 
Do we need to do anything after calling SurveyTemplateText (e.g. render(), etc)?

**Comment by dmitrykurmanov** [comment]
May be the problem in bootstrap.js. Could you check it please https://github.com/andrewtelnov/surveyjs/issues/104 ?

**Comment by Aleyasen** [comment]
It works like a charm, Thanks :)

**Comment by Daggb** [comment]
@dmitrykurmanov I also need to add $data.value as a css class I managed to do it like this: 

`new Survey.SurveyTemplateText().replaceText('<div class="btn-group"> <label class="btn btn-default" data-bind="css:{$data.value}, style:{width: question.koWidth}">   <input type="radio" style="display:none;" data-bind="attr: {name: question.name, value: item.value}, checked: question.koValue" /> <span data-bind="text: item.text"></span></label><div data-bind="visible:question.hasOther"><div data-bind="template: { name: \'survey-comment\', data: {\'question\': question, \'visible\': question.koOtherVisible } }"></div></div></div>', "question", "radiogroup");
new Survey.SurveyTemplateText().replaceText('<div class="btn-group"> <label class="btn btn-default" data-bind="css:{$data.value}, style:{width: question.koWidth}">   <input style="display:none;" type="checkbox" data-bind="attr: {name: question.name, value: item.value}, checked: question.koValue" /> <span data-bind="text: item.text"></span></label><div data-bind="visible:question.hasOther"><div data-bind="template: { name: \'survey-comment\', data: {\'question\': question, \'visible\': question.koOtherVisible } }"></div></div></div>', "question", "checkbox");
`

Now that I'm using

 ` data-bind="css:{active: $data.value == question.koValue()}`

I can't add the second class, I tried to add it in the attr: but it overwrite the class="btn ban-dafault"

What could be the best approach to add the $data.value as a class?
