### ISSUE TITLE
survey.bootstrap.js:163 Refused to set unsafe header "Content-Length"

### ISSUE THREAD

**Issue by KrishnaPG** [andrewtelnov/surveyjs#11]
Encountering this error on clicking complete.
> Refused to set unsafe header "Content-Length"
![image](https://cloud.githubusercontent.com/assets/4610831/15560837/34cc4394-230d-11e6-9659-98f05751606d.png)

**Comment by andrewtelnov** [comment]
According to: http://stackoverflow.com/questions/7210507/ajax-post-error-refused-to-set-unsafe-header-connection, I have removed the "Content-Length" setting.
Could you please rebuilt the library and check, does it work?

Thank you,
Andrew

**Comment by KrishnaPG** [comment]
Thank you. Checked with latest build and could not see the error.
