### ISSUE TITLE
onValidateQuestion didn't work properly when I used a ajax call in it

### ISSUE THREAD

**Issue by Aleyasen** [andrewtelnov/surveyjs#119]
I need to implement a validation from server side, so I used the following code:
```js
survey.onValidateQuestion.add(function (s, options) {
    if (options.name == 'code') {
        var codeVal = options.value;
        console.log(codeVal);
        $.ajax({url: 'verify.php',
            data: {code: codeVal},
            type: 'post',
        }).done(function (data) {
            console.log(data);
            options.error = "error1";
        }).fail(function (data) {
            console.log(data);
            options.error = "error2";

        });
    }
```
but the validation doesn't work, I mean however I set ```optoins.error``` in both done and fail method, but it doesn't show my any error and it submits the form successfully without any error that is not desired.

**Comment by andrewtelnov** [comment]
@Aleyasen It works properly. Unfortunately, it doesn't support your scenario. The code continue to work after ajax request has been called. As result, when ajax request comes back to the client, a next page is shown or survey is completed.
The scenario is valid. I need some time to find a solution. Probably it will require some code modification in the library. Something like, wait until ajax request is performed.

Thank you,
Andrew

**Comment by Aleyasen** [comment]
Yes, you're right. I forgot about the callback.

**Comment by andrewtelnov** [comment]
@Aleyasen I have implemented this functionality. Could you please take a look? https://github.com/andrewtelnov/surveyjs/issues/137
