### ISSUE TITLE
How can we add a new property for a specific question or to all

### ISSUE THREAD

**Issue by gilbertsalloum** [andrewtelnov/surveyjs#120]
I want to add a new property to all the questions or to each question type by its own
Example
i need to add a checkbox isMobile like the visible option for each question to each question so i know later on if this should be shown to mobile version or not.

can you explain what i should do in order to do so.
Thanks

**Comment by andrewtelnov** [comment]
@gilbertsalloum do you want be able to parse this value in json and see in visual editor?
There is no public API for it, but I may add it, if it is what you are looking for: Ability to add custom properties to survey questions.

**Comment by gilbertsalloum** [comment]
hello man
sorry for the delay
yes this is actually what i need if you can add that it would be great thanks.

**Comment by andrewtelnov** [comment]
@gilbertsalloum Got it. I hope to find a time and do it on the next week.
And I have another question. Do you actually looking for a feature, that will tell modify survey based on device type: show/hide questions if they are "desktop" or "mobile" only.

**Comment by gilbertsalloum** [comment]
@andrewtelnov  thank you for your reply

actually let me explain our 

We are creating a form that the user will be using to purchase an insurance policy (life,motor,...)
in some of the policies we will need to oblige the user to fill some of the data using his mobile device (in case of Motor he will upload photos of the vehicle...)
what we are trying to do is adding a new property for each question if this question should be visible in desktop front end or the mobile or both

hopefully this explains our problem.

**Comment by andrewtelnov** [comment]
I have implemented the functionality: https://github.com/andrewtelnov/surveyjs/issues/135

**Comment by andrewtelnov** [comment]
I believe this feature will be useful as well: https://github.com/andrewtelnov/surveyjs/issues/136

**Comment by gilbertsalloum** [comment]
hey man thank you for your update
Great Job

**Comment by franjogordillo** [comment]
Hi Andrew can you please tell me in which file can i find the question properties , i want to delete a few properties.

**Comment by andrewtelnov** [comment]
@franjogordillo I guess, you are talking about the surveyjs Editor. Am I right?

**Comment by franjogordillo** [comment]
Yes Andrew in the GUI part (survey editor), for examplo how can i remove the indent property

**Comment by andrewtelnov** [comment]
@franjogordillo I will work on the example that shows how to do it. Likely, I will have to add some functionality to the Editor. Please refer to this [issue](https://github.com/andrewtelnov/surveyjs.editor/issues/32)
