### ISSUE TITLE
React doesn't correctly update question numbers when a questions are shown/hidden

### ISSUE THREAD

**Issue by jdalegonzalez** [andrewtelnov/surveyjs#121]
Given the following survey definition json...

```javascript
{
 pages: [
  {
   name: "page1",
   questions: [
    {
     type: "radiogroup",
     choices: [
      "one",
      {
       value: "two",
       text: "second value"
      },
      {
       value: "three",
       text: "third value"
      }
     ],
     name: "question1"
    },
    {
     type: "text",
     name: "question2",
     title: "Showing and hiding",
     visibleIf: "{question1}==\"one\""
    },
    {
     type: "text",
     name: "question3",
     title: "Always here"
    },
    {
     type: "text",
     name: "question4",
     title: "Also, always here"
    }
   ]
  }
 ]
}
```
Selecting "one" on the first question shows the second question, selecting anything else hides the second question.  When the second question is displayed, question3 and question4 aren't renumbered.  The survey questions are numbered "1, 2, 2, 3".  Change the value of any of the questions will reset its number to the correct value.   ie. Changing the value for question3  will cause it to be renumbered to "3".  However, hiding question2 again will leave question3 with the updated number  ie. the survey will now be numbered 1, 3, 3.

Renumbering works correctly on the test page of the survey designer.  Perhaps this is a react only problem

**Comment by jdalegonzalez** [comment]
... I forgot to mention but the "complete" button doesn't update correctly either if the visibility of the last page is toggled.  For example, if you're on page2 and page3 is hidden, you would expect to see a previous button and complete button.  Doing something on page2 that shows page3 should cause the complete button to now say "next".  This doesn't work in react.

**Comment by andrewtelnov** [comment]
@jdalegonzalez yes, the bug with buttons and progress was in both versions: knockout and react.
I have fixed it: https://github.com/andrewtelnov/surveyjs/issues/123.

Thank you,
Andrew
