### ISSUE TITLE
Where is the [resultId] UUID for use with dxsurvey.com ?

### ISSUE THREAD

**Issue by starlocke** [andrewtelnov/surveyjs#127]
The dxsurvey API method "getResult" requires [resultId] and [name] to work. I think I see where to get [name], but where can [resultId] be found?

Finding [name] on dxsurvey.com : 

> [Screenshot](http://i.imgur.com/mQpXtvn.png)

API documentation for "getResult" :

> http://api.dxsurvey.com/Help/Api/GET-api-Survey-getResult_resultId_name

**Comment by dmitrykurmanov** [comment]
Could you check it please?

http://dl1.joxi.net/drive/2016/11/25/0019/3026/1289170/70/8243e160fb.jpg

**Comment by starlocke** [comment]
@dmitrykurmanov Dude, sweet! Thank you very much!!

I never expected that "chevron" to be a toggle! Gosh, I hate "ultra-low-key, practically-hidden" UI elements like that.
