### ISSUE TITLE
Feature Request : Matrix question with flexible input type.

### ISSUE THREAD

**Issue by mirmdasif** [andrewtelnov/surveyjs#13]
Hi first of all thanks for this awesome library. It's awesome and very promising. I convinced my team to use it production, good job.

In my use cases there is a scenario where I need a matrix or tabular question. And cells can not only be drop down's and radio but  can also be text input, check boxes etc. I think it will be a handy feature for all.

**Comment by andrewtelnov** [comment]
Hi,
Yes, I agree that it would be useful.
Do you have any deadlines? I have not much times on this week, I may take a look on this feature on the next week. 
If you provide the exact scenario(s), it would be helpful. I need to make a good example to show others how it works and how it could be used.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
I am going to implement the following types: ["dropdown", "checkbox", "radiogroup", "text"].

**Comment by andrewtelnov** [comment]
I have committed the version with new cellType property in the matrixDropdownColumn.
I do not rebuild js and npm version. I have to change the editor. You may build the library by yourself.
Here is the supported json, please take a look at cellType property.
```
{questions: [
{ type: "matrixdropdown", name: "frameworksRate", title: "Please tells us your opinion about JavaScript MVVM frameworks",
    choices: ["Excelent", "Good", "Average", "Fair", "Poor"],
    columns: [{ name: "using", title: "Do you use it?", choices: ["Yes", "No"], cellType: "radiogroup" }, 
              { name: "experience", title: "How long do you use it?", choices: [{value: 5, text:"3-5 years"}, {value: 2, text:"1-2 years"}, {value: 1, text:"less then a year"}] }, 
              { name: "strength", title: "What is main strength?", choices: ["Easy", "Compact", "Fast", "Powerfull"], cellType: "checkbox" }, 
              { name: "knowledge", title: "Please describe your experience", cellType:"text" },
              { name: "rate", title: "Please rate the framework itself" }],
    rows: [{ value: "angularv1", text: "angularjs v1.x" }, 
           { value: "angularv2", text: "angularjs v2" },
           { value: "knockoutjs" }, 
           { value: "reactjs"}]}
]}
```

**Comment by andrewtelnov** [comment]
Here we are: http://surveyjs.org/examples/questiontype-matrixdropdown.html

Thank you,
Andrew
