### ISSUE TITLE
visibleIf compares numbers from text-type questions like strings

### ISSUE THREAD

**Issue by klvbdmh** [andrewtelnov/surveyjs#140]
**Steps to reproduce the issue**:

1. Paste the following code in the [JSON Editor](http://surveyjs.org/builder/):

```
{
 pages: [
  {
   name: "page1",
   questions: [
    {
     type: "text",
     name: "Number",
     title: "Enter a number",
     validators: [
      {
       type: "numeric"
      }
     ]
    },
    {
     type: "html",
     html: "<p>Greater than 1200</p>",
     name: "Greater",
     visible: false,
     visibleIf: "{Number} > 1200"
    },
    {
     type: "html",
     html: "<p>Less than 1200</p>",
     name: "Less",
     visible: false,
     visibleIf: "{Number} < 1200"
    }
   ]
  }
 ]
}
```
2. In the Test Survey tab enter the following values: `2`, `100`, `11111`, `gggg`. After entering each value press Enter.

**Expected behavior**

* When entering `2`, the text underneath should say `Less than 1200`.
* When entering `100`, the text underneath should say `Less than 1200`.
* When entering `11111`, the text underneath should say `Greater than 1200`.
* When entering `gggg`, the text underneath shouldn't say anything, as we already include validator for numerical values.

**Observed behavior**

* When entering `2`, the text underneath says `Greater than 1200`.
* When entering `100`, the text underneath says `Less than 1200`.
* When entering `11111`, the text underneath says `Less than 1200`.
* When entering `gggg`, the text underneath says `Greater than 1200`.

**Notes**

Text is the only question type that allows entering custom numerical values, for example salary or car mileage. It looks like the values are compared like strings instead of numerical values. The current behavior is a major problem when using numerical value to customize survey logic.

**Comment by andrewtelnov** [comment]
@klvbdmh I may add inputType property to the QuestionText class.
The default is "text". There will be "numeric", "date", "datetime" and other options.
Will it work for you?

**Comment by andrewtelnov** [comment]
@klvbdmh However, I can see, there is an issue with numeric validator as well. I will look at it. Thank you.

**Comment by klvbdmh** [comment]
@andrewtelnov 
> I may add inputType property to the QuestionText class.

That would be fantastic.

**Comment by andrewtelnov** [comment]
@klvbdmh It is implemented: https://github.com/andrewtelnov/surveyjs/issues/141

**Comment by andrewtelnov** [comment]
@klvbdmh validation works as expected. It is executed on clicking page next and complete.
I have tried your json with inputType: "number" and it works as expected now. Plus Chrome shows nice spin buttons.
I think, it is a better solution.

**Comment by klvbdmh** [comment]
Yes, changing inputType to "number" works great now. Thank you.
