### ISSUE TITLE
add inputType property into Text Question

### ISSUE THREAD

**Issue by andrewtelnov** [andrewtelnov/surveyjs#141]
inputType property, default value is "text".
Possible values are: "color", "date", "datetime", "datetime-local", "email", "month", "password", "range", "tel", "text", "time", "url", "week".

**Comment by andrewtelnov** [comment]
It is implemented

**Comment by klvbdmh** [comment]
I can't find "number" on the dropdown menu. Manually writing it in JSON editor works. Am I missing something?
![surveyjs-number](https://cloud.githubusercontent.com/assets/10261718/20842441/e2975d66-b8b7-11e6-9719-288ac7afd122.png)

**Comment by andrewtelnov** [comment]
@klvbdmh I can't believe I have missed "number" in the choices.
Fixed.

**Comment by SaraaAwwad** [comment]
Hello,
How can I hide one of those properties? for example: i dont want "email" to be shown in the choices.
Thank you.

**Comment by andrewtelnov** [comment]
@SaraaAwwad Are you asking about SurveyJS Creator? You can set your choices or update the current.
`Survey.findProperty("text", "inputType").choices = youArrayOfInputTypes;`

Thank you,
Andrew

**Comment by SaraaAwwad** [comment]
I did, but I'm facing this error:
" ERROR TypeError: Cannot set property choices of [object Object] which has only a getter "
