### ISSUE TITLE
Matrix (dynamic rows) with various control type

### ISSUE THREAD

**Issue by shahromil88** [andrewtelnov/surveyjs#157]
Hi,

I really liked the Matrix (dynamic rows) component provided. However, It supports only single control for all columns via cellType property. Is there any planning to introduce configuration for multiple controls such as TextInput for Column# 1, Dropdown for Column# 2 etc?

Cheers,
Romil

**Comment by andrewtelnov** [comment]
@shahromil88 Of course, it is possible, just take a look at [the example](http://surveyjs.org/examples/questiontype-matrixdynamic.html)

**Comment by shahromil88** [comment]
Thanks. It is exactly what I want.
