### ISSUE TITLE
non ascii chars are not escaped in the JSON generated by the visual editor

### ISSUE THREAD

**Issue by Frank13** [andrewtelnov/surveyjs#17]
Plain copy/paste can cause encoding errors
UTF-8 seems not being supported by JSON5
Could you add a replace for accentuated chars like é->\u00e9 ? so that the problem is avoided once for all?

**Comment by andrewtelnov** [comment]
Hi,
I have probably missed something. I have tried to insert the symbol: 'é' into JSON editor and change page tittle to 'ééééé', it works fine. I have tried: Chrome, Edge, IE 11, Firefox, and Opera.
I have seen surveys, created in dxsurvey.com (it uses same editor), using difference western/eastern European languages. There are surveys in hieroglyphics. My friend, several days ago, ran a survey in Cyrillic. Everything was fine.
If I do automatic conversion, titles, names become unreadable. Some people will be definitely unhappy, and will complain.
Could you, please, describe in more details, what is going on?

Thank you,
Andrew

**Comment by Frank13** [comment]
Hello Andrew,

Thx for your quick answer.
My problem is linked to the fact that I use the python version of Google 
App Engine and python is not tolerant on charsets.
I have found a bypass with an Eclipse plug-in that makes the conversion 
to unicode escaped strings by a single right click.

Your module seems really great. If you need some help for French 
localization. Don't hesitate to ask.

Kind regards

Frank

**Comment by andrewtelnov** [comment]
Hello Frank,
It is great, that you was able to solve the issue!
About localization: of course, It would be awesome, if you share you French localization with others. You may send it to me, I will create a French.ts file here: https://github.com/andrewtelnov/surveyjs/tree/master/src/localization, and provide a link to your GitHub account, to the author.
However, it would be better, if you do a pull request with your own French.ts file (similar to other files in localization directory). I will definitely accept it.

Thank you,
Andrew

**Comment by Frank13** [comment]
Hello Andrew,

Hopes this helps.

Kind regards

Frank

**Comment by andrewtelnov** [comment]
Hello, 
I believe there should be an attachment or additional text.

Thank you,
Andrew

**Comment by Frank13** [comment]
Seems the attached piece was filtered out, so I inlined it.
Best
Frank

/// <reference path="..//surveyStrings.ts" />
module Survey {
     var frenchSurveyStrings = {
         pagePrevText: "Pr\u00e9c\u00e9dent",
         pageNextText: "Suivant",
         completeText: "Terminer",
         otherItemText: "Autre (pr\u00e9ciser)",
         progressText: "Page {0} sur {1}",
         emptySurvey: "Il n'y a ni page visible ni question visible dans 
ce questionnaire",
         completingSurvey: "Merci d'avoir r\u00e9pondu au questionnaire!",
         loadingSurvey: "Le questionnaire est en cours de chargement...",
         optionsCaption: "Choisissez...",
         requiredError: "La r\u00e9ponse \u00e0 cette question est 
obligatoire.",
         numericError: "La r\u00e9ponse doit \u00eatre un nombre.",
         textMinLength: "Merci d'entrer au moins {0} symboles.",
         minSelectError: "Merci de s\u00e9lectionner au moins {0} 
r\u00e9ponses.",
         maxSelectError: "Merci de s\u00e9lectionner au plus {0} 
r\u00e9ponses.",
         numericMinMax: "Votre r\u00e9ponse '{0}' doit \u00eatre 
sup\u00e9rieure ou \u00e9gale \u00e0 {1} et inf\u00e9rieure ou 
\u00e9gale \u00e0 {2}",
         numericMin: "Votre r\u00e9ponse '{0}' doit \u00eatre 
sup\u00e9rieure ou \u00e9gale \u00e0 {1}",
         numericMax: "Votre r\u00e9ponse '{0}' doit \u00eatre 
inf\u00e9rieure ou \u00e9gale \u00e0 {1}",
         invalidEmail: "Merci d'entrer une adresse mail valide.",
         exceedMaxSize: "La taille du fichier ne doit pas exc\u00e9der 
{0}.",
         otherRequiredError: "Merci de pr\u00e9ciser le champ 'Autre'."
     }
     surveyLocalization.locales["fr"] = frenchSurveyStrings;
}

**Comment by andrewtelnov** [comment]
Great!
Here we are: https://github.com/andrewtelnov/surveyjs/blob/master/src/localization/french.ts
Thank you!

**Comment by Frank13** [comment]
Thanks,

I have noticed a slight bug. When changing to the next page, the page 
should be scrolled up.

Kind regards

Frank

**Comment by andrewtelnov** [comment]
I have created a new issue: https://github.com/andrewtelnov/surveyjs/issues/23

Thank you,
Andrew

**Comment by Frank13** [comment]
Hello Andrew,

Seems that there is a descrepency between what I sent to you :
Le 15/06/2016 à 20:47, Frank Derville a écrit :
> requiredError: "La r\u00e9ponse \u00e0 cette question est obligatoire.",

and the result below : the space between "est" and "obligatoire" has 
disapeared. Copy paste error or bug?

Kind regards
Frank

**Comment by andrewtelnov** [comment]
Yes, it was my mistake. The text copied with new lines and I did not replace them properly for this string.
I have committed the correction.

Thank you,
Andrew

**Comment by Frank13** [comment]
Hello Andrew,

Another issue I have found but this time in the dxSurvey Service : the 
.xlsx export of rating questions is exported to text instead of number.

Kind regards

Frank

**Comment by andrewtelnov** [comment]
Hello Frank,
I have create the bug report: https://github.com/andrewtelnov/surveyjs/issues/26
I will take a look at it.
Thank you,
Andrew

**Comment by Frank13** [comment]
Hi Andrew,

Sorry to send you bugs one by one ;-( but I have no time to do an 
extensive test.
The dxSurvey service has an other problem (major). It does not export 
checkbox question results in whatever the format (CSV, XLS, XLSX).

Kind regards

Frank

**Comment by andrewtelnov** [comment]
Hi Frank,
Thank you for reporting the issue! Yes, it was my mistake. It is fixed now.

Thank you,
Andrew
