### ISSUE TITLE
otherRequiredError for localization "de" is missing

### ISSUE THREAD

**Issue by whity76** [andrewtelnov/surveyjs#18]

**Comment by andrewtelnov** [comment]
I have committed the updated locale strings for de:
https://github.com/andrewtelnov/surveyjs/blob/master/src/localization/german.ts
Deutsch is not my native language, Could you please check the localization and correct if needed?

Thank you,
Andrew

**Comment by whity76** [comment]
your translation was great, I just changed a few little things and typos.

**Comment by andrewtelnov** [comment]
Could you make a pull request? I would love to correct the "de" localization.

Thank you,
Andrew
