### ISSUE TITLE
"Invalid shorthand property initializer" - jQuery

### ISSUE THREAD

**Issue by mellogarrett** [andrewtelnov/surveyjs#188]
Getting this error on the line `onComplete={sendDataToServer}`

<img width="587" alt="error" src="https://cloud.githubusercontent.com/assets/9908831/22038574/be5f864a-dcc9-11e6-9517-69f3c9a80d19.png">

**Comment by dmitrykurmanov** [comment]
Hello! You have a syntax error. Please try this:

**Comment by mellogarrett** [comment]
Thanks for the comment! That fixed it. 

The jQuery documentation on the front page is wrong.

**Comment by andrewtelnov** [comment]
@mellogarrett Yes, you are right. The documentation on the first page had the error. It was fixed.
Thank you,
Andrew

**Comment by mellogarrett** [comment]
Thanks @andrewtelnov! Any reason you left the brackets around the function name?

**Comment by dmitrykurmanov** [comment]
@mellogarrett , no reason in brackets. Fixed it. Thank you.
