### ISSUE TITLE
Specify "Thank You" message

### ISSUE THREAD

**Issue by mellogarrett** [andrewtelnov/surveyjs#189]
Is it possible to provide a message in the JSON file to overwrite the default "Thank You for Completing the Survey!" message?

**Comment by JonBetts** [comment]
Yeah I tried to do this but it didn't seem to override the default value.

**Comment by andrewtelnov** [comment]
@mellogarrett @JonBetts There is a completedHtml property in the survey object. Please take a look at this example: http://surveyjs.org/examples/jquery/survey-processtext.html

**Comment by JonBetts** [comment]
Doesn't the 'Thank You for Completing the Survey!' message get stored in the variable 'completingSurvey'? Could that not potentially be overridden in the main properties of the survey being created?

**Comment by mellogarrett** [comment]
```
$("#survey").Survey({
          model: survey,
          onComplete: sendDataToServer,
          completedHtml: "some new message"
});
```
This didn't change anything for me

**Comment by mellogarrett** [comment]
Thanks @andrewtelnov! Passing it in the survey model with the key of `completedHtml` did the trick.
