### ISSUE TITLE
"other" value

### ISSUE THREAD

**Issue by whity76** [andrewtelnov/surveyjs#19]
is it possible to get rid off the value "other"?

i think it's better to add the entered value in the data for the field directly.

as fas as i can see it seems to me that "other" is added to the fielddata and the entered data is 
submitted as new "..-comment" field.

**Comment by andrewtelnov** [comment]
That is questionable. It depends what you are doing with the survey.
In surveys I needed, I would love to have the other value separate. If a lot of people are choosing other, it means that I need to correct the question choices accordingly. 
I can easily find it out: choice1 - 15%, ...,choice N - 5%, other - 30%. If I have the value directly the choice field - it will be hard to find out, what is wrong.
However, I do agree, that it may be useful in some cases. 
If I introduce a property: storeOthersInComment (true by default) on survey level. will it work for you?

Thank you,
Andrew

**Comment by whity76** [comment]
that would be very great and i guess it would make sense for at least some use-cases.
thx a lot!

**Comment by andrewtelnov** [comment]
I have committed the changes. survey.storeOthersAsComment (default is true) should be set to false. Could you try it out? You should build the library from sources.

Thank you,
Andrew
