### ISSUE TITLE
Nested hidden triggers

### ISSUE THREAD

**Issue by ZakMiller** [andrewtelnov/surveyjs#195]
We are facing a situation where we have three questions. If question 1 (Q1) is answered a certain way, Q2 appears. If Q2 is answered a certain way, Q3 appears. 

This all works with triggers that change the 'hidden' value.

The problem is that if someone changes their answer to Q1, Q2 disappears but Q3 stays there.

Is there a way to fix this? Perhaps undo all triggers affected by a question answer when that question is hidden?

**Comment by andrewtelnov** [comment]
@ZakMiller Yes, trigger will not work for you in this case. They are just trigger an event and perform an action. 
I would suggest to used the visibleIf property.
For Q2.visibleIf = "{Q1} = 'val1'"; and for Q3.visibleIf = "{Q1} = 'val1' and {Q2} = 'val2'";
That should work fine. Here the demo that shows exactly what you need: http://surveyjs.org/examples/jquery/condition-kids.html

Thank you,
Andrew

**Comment by ZakMiller** [comment]
@andrewtelnov Thank you andrew. We were using an older version of surveyjs. Didn't realize this was a feature. It works perfectly!
