### ISSUE TITLE
Unable to save created Survey

### ISSUE THREAD

**Issue by vankayalapatisai** [andrewtelnov/surveyjs#197]
I am trying to just see save functionality  after creating surveys. But its not visible and no error or warnings available.

**Comment by andrewtelnov** [comment]
@vankayalapatisai Could you please provide more information? You are able to render the surveyjs on your page, aren't you? What version and framework do you use?

Thank you,
Andrew

**Comment by vankayalapatisai** [comment]
Hi Andrew,
here's link http://surveyjs.org/builder/
from here i was not able to find save button.

**Comment by andrewtelnov** [comment]
@vankayalapatisai That is correct. You have to use dxsurvey.com service to save/load survey in the cloud.
The current page allows you to built a survey and copy survey JSON in the "Survey JSON" tab or copy the code into your web page from the "Embed Survey" tab.

**Comment by vankayalapatisai** [comment]
Hi thanks Andrew. 
Yes I could able to save survey :) .
