### ISSUE TITLE
Feature Request: Matrix Question With Dynamic Row add Remove Functionality  

### ISSUE THREAD

**Issue by mirmdasif** [andrewtelnov/surveyjs#34]
Screenshot Of the Feature

![screenshot-localhost 8000 2016-07-13 13-47-30](https://cloud.githubusercontent.com/assets/957058/16804418/893279d0-492d-11e6-9765-d72d9179cf67.png)

Basic feature implemented for knockout

https://github.com/mirmdasif/surveyjs/tree/feature/dynamic-row-in-matrix-dropdwon

**Comment by andrewtelnov** [comment]
I have just committed the react version and I believe I have done with it. Could you please check it out?

I am going to add examples with this question a little later.

Thank you,
Andrew

**Comment by mirmdasif** [comment]
Hi I have tested matrixdynamic dynamic question. So far so good :).

Just one suggestion default value for rowCount is 2. But I think it should be length of data if given or 1. This way user don't have to pass different rowCount every time. 

We store survey definition in a template which does not change. For every users only difference is the survey data. Just a suggestion not a big deal.

**Comment by andrewtelnov** [comment]
How bad do you need it? I am using incremental row index as an unique id. I can't use just index in the row, because I do not want to recreate all rows on deleting or synchronize indexes.

Thank you,
Andrew

**Comment by mirmdasif** [comment]
Honestly speaking I don't need it at all. I have modified my code in such a way that rowCount for a matrixdynamic question is always equals to the length of data. So you may or may not address it as a issue :)

**Comment by andrewtelnov** [comment]
Great! :)

**Comment by andrewtelnov** [comment]
[Example](http://surveyjs.org/examples/questiontype-matrixdynamic.html)
