### ISSUE TITLE
Survey Property :  postInvisibleQuestions : boolean (default is true)

### ISSUE THREAD

**Issue by mirmdasif** [andrewtelnov/surveyjs#35]
Prevents hidden question to be submitted.

Possible scenario

Q1. Do you have a car ? a. yes b. no
If yes Q2: What's the color of your car?
Now if no is selected then there's no meaning of Q2

**Comment by andrewtelnov** [comment]
Hi,
Yep, it looks like it makes sense.

**Comment by andrewtelnov** [comment]
I have added clearInvisibleValues property, default value is false. If it is true, survey clears all invisible question values before firing onComplete event or sending data to a server.

Thank you,
Andrew

**Comment by mirmdasif** [comment]
Tested no issues.
