### ISSUE TITLE
Add new property to survey: goNextPageOnQuestionsComplete 

### ISSUE THREAD

**Issue by andrewtelnov** [andrewtelnov/surveyjs#37]
It is false by default. If it sets to true, after all questions on page are completed and there is no errors - go to the next page or complete the survey.

**Comment by andrewtelnov** [comment]
survye.goNextPageAutomatic property (default is false) is added. On answering all questions on the page, the survey will go automatically to the next page or complete the survey.

**Comment by andrewtelnov** [comment]
[Example](http://surveyjs.org/examples/survey-autonextpage.html)

**Comment by ItsJoeTurner** [comment]
I'm having some issues with this when answering checkbox questions. The first option takes the user to the next page but the reality is that there could be more than one answer. Can we have a .goToNextPageAutomatic on the individual questions as well as pages?

**Comment by andrewtelnov** [comment]
It is a bug. I will work on the fix: https://github.com/andrewtelnov/surveyjs/issues/70

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
The bug was fixed.
