### ISSUE TITLE
Multiple Criteria in trigger

### ISSUE THREAD

**Issue by mfarazkhan** [andrewtelnov/surveyjs#39]
Hi,

Could you please add Multiple statement feature to execute a single trigger, criteria could be 'n' numbers of statements for a single trigger.
for e,g; 
if(Age > 24 And Gender == 'Male')
{
//visible trigger
}

Thanks for a wonderful survey engine.

Thanks,
Muhammad Faraz Khan

**Comment by andrewtelnov** [comment]
Please refer to this: https://github.com/andrewtelnov/surveyjs/issues/60
