### ISSUE TITLE
Other value for matrix question column

### ISSUE THREAD

**Issue by mirmdasif** [andrewtelnov/surveyjs#40]
Hi dropdown and checkboxes in matrix question do not have other value property which seems a valid scenario.

**Comment by andrewtelnov** [comment]
It is implemented. The hasOther property is added to a column object.

**Comment by mirmdasif** [comment]
Hi other value for checkboxes in dynamic table seems to be broken.

**Comment by andrewtelnov** [comment]
Yes, thank you!
The issue is fixed. Please check it out.

Thank you,
Andrew

**Comment by mirmdasif** [comment]
Thanks it's fixed now :)
