### ISSUE TITLE
Multiple trigger not working for checkboxes

### ISSUE THREAD

**Issue by mirmdasif** [andrewtelnov/surveyjs#45]
Sample json working on survey builder broken in latest build
{
 pages: [
  {
   name: "page1",
   questions: [
    {
     type: "checkbox",
     choices: [
      "one",
      {
       value: "two",
       text: "second value"
      },
      {
       value: "three",
       text: "third value"
      }
     ],
     name: "question1"
    },
    {
     type: "text",
     name: "question2",
     visible: false
    },
    {
     type: "text",
     name: "question3",
     visible: false
    },
    {
     type: "text",
     name: "question4",
     visible: false
    }
   ]
  }
 ],
 triggers: [
  {
   type: "visible",
   operator: "contains",
   value: "one",
   name: "question1",
   questions: [
    "question2"
   ]
  },
  {
   type: "visible",
   operator: "contains",
   value: "two",
   name: "question1",
   questions: [
    "question3"
   ]
  }
 ]
}

**Comment by mirmdasif** [comment]
Screenshot from survey builder site release version v0.9.9
![screenshot-surveyjs org 2016-07-31 19-59-39](https://cloud.githubusercontent.com/assets/957058/17276980/9c97ed2c-5759-11e6-97d7-cf033ec981d5.png)

Screenshot from latest build

![screenshot-localhost 63343 2016-07-31 20-00-37](https://cloud.githubusercontent.com/assets/957058/17276990/cbab7e44-5759-11e6-9b90-8e5c78c9bd08.png)
![screenshot-localhost 63343 2016-07-31 20-00-18](https://cloud.githubusercontent.com/assets/957058/17276991/cbad1c18-5759-11e6-8c1e-08ceaf3d613a.png)

**Comment by andrewtelnov** [comment]
Yes, indeed. The survey checkbox value was stored in the survey data as a link on itself. As result they are modifying at the same time and the new check doesn't work.
I have written the unit test and fix it.
Thank you very much!
Andrew-
