### ISSUE TITLE
question fullTitle is incorrect if survey.showQuestionNumber is "off"

### ISSUE THREAD

**Issue by andrewtelnov** [andrewtelnov/surveyjs#48]
If survey.showQuestionNumber set to 'off' the question title has the dot '.' at the beginning: '. [questionTitle]'. 
Workaround: in the current version (v0.9.10) use survey.questionTitleTemplate: "{require} {title}";

**Comment by andrewtelnov** [comment]
Fixed-

**Comment by Xcellion** [comment]
Thanks!
