### ISSUE TITLE
Visible triggers should clear question's answer. Issue in multi level dependent question.

### ISSUE THREAD

**Issue by mirmdasif** [andrewtelnov/surveyjs#49]
Here's the scenario. 
-Q1
 ---Q2
 --------Q3

Q1's answer triggers Q2. Q2's answer triggers Q3.
Now first user answer Q1 which makes Q2 visible. Then answer Q2 which makes question Q3 visible.
Now if user change answer of Q1 it will make Q2 invisible but as Q2's answer is not cleared Q3 will be visible. Which is kind of illegal state.

Q1
---------Q3

Here's the json to reproduce the scenario.
Steps: 
Q1 = 1
Q2 = 1
Q3 = 1
now before submitting set 
Q1 = 2

{
 clearInvisibleValues: true,
 pages: [
  {
   name: "page1",
   questions: [
    {
     type: "radiogroup",
     choices: [
      "one",
      {
       value: "two",
       text: "second value"
      },
      {
       value: "three",
       text: "third value"
      }
     ],
     name: "question1"
    },
    {
     type: "radiogroup",
     choices: [
      "one",
      {
       value: "two",
       text: "second value"
      },
      {
       value: "three",
       text: "third value"
      }
     ],
     indent: 1,
     name: "question2",
     visible: false
    },
    {
     type: "radiogroup",
     choices: [
      "one",
      {
       value: "two",
       text: "second value"
      },
      {
       value: "three",
       text: "third value"
      }
     ],
     indent: 2,
     name: "question3",
     visible: false
    }
   ]
  }
 ],
 triggers: [
  {
   type: "visible",
   operator: "equal",
   value: "one",
   name: "question1",
   questions: [
    "question2"
   ]
  },
  {
   type: "visible",
   operator: "equal",
   value: "one",
   name: "question2",
   questions: [
    "question3"
   ]
  }
 ]
}

**Comment by andrewtelnov** [comment]
Hi,
Well, the question2 still equals 'one', even after it becomes invisible You may use the setValue trigger, to make the 'question2' empty. Please take a look at: http://surveyjs.org/builder/?surveyid=4be0c4b3-a6f5-472b-a097-f8886acceed8 
Will it work for you?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Please take a look at this demo: http://surveyjs.org/examples/condition-kids.html.
It should do exactly, what you needed.
