### ISSUE TITLE
Wrong CSS styles for links

### ISSUE THREAD

**Issue by mattes3** [andrewtelnov/surveyjs#53]
In survey.css there is:

.sv_window_title a, a:link, a:visited {
  text-decoration: none;
  font-size: 14px;
  font-style: normal;
  color: black; }

That hits too many "a"-tags, also outside of the survey markup. The correct styling probably is this:

.sv_window_title a {
  text-decoration: none;
  font-size: 14px;
  font-style: normal;
  color: black; }

.sv_window_title a:link {
  text-decoration: none;
  font-size: 14px;
  font-style: normal;
  color: black; }

.sv_window_title a:visited {
  text-decoration: none;
  font-size: 14px;
  font-style: normal;
  color: black; }

**Comment by andrewtelnov** [comment]
Yes, you are right. I should pay more attention to the non-bootstrap css.

**Comment by andrewtelnov** [comment]
It is fixed.
Thank you,
Andrew

**Comment by mattes3** [comment]
Thanks, Andrew!
