### ISSUE TITLE
Question with an address input form

### ISSUE THREAD

**Issue by mattes3** [andrewtelnov/surveyjs#54]
Is it possible to render a question that asks for a postal address?

Something like this (screenshot attached):

![screen shot 2016-08-22 at 13 57 23](https://cloud.githubusercontent.com/assets/2496674/17854085/7d76a2c6-6870-11e6-9e21-a807d6e735dc.png)

**Comment by andrewtelnov** [comment]
Hi,
There is a width property, that should make it work. It has the default value is 100%, but it can be 50%. Unfortunately, it doesn't work. I have just checked it. I will try to fix it on this week.

There is no ability to show question label under a question. Do you need this functionality? Do you need it on the survey level or page level?

Thank you,
Andrew

**Comment by mattes3** [comment]
Having a separate label under a question would be a nice feature.

What do you mean by "on the survey level or page level" ?

**Comment by andrewtelnov** [comment]
Survey level: title will be placed under questions for entire survey.
Page level: title will be placed under questions for a specific page. You will have to set the property for every page, in case you want to change it for all questions in the survey.

**Comment by andrewtelnov** [comment]
I will try to implement the same layout in a demo. I will keep you inform. I will likely do it on the next week, The width property will not make a trick. It should be something like, "keep on the same line" property.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
The first feature is implemented: https://github.com/andrewtelnov/surveyjs/issues/64

**Comment by andrewtelnov** [comment]
FYI: I am working on several questions in one row (single line). I hope to show something in couple days.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
The fun is starting when the question visibility is changed :)

**Comment by andrewtelnov** [comment]
https://github.com/andrewtelnov/surveyjs/issues/65
I have to change the survey visual editor now to finish with the feature.

**Comment by andrewtelnov** [comment]
It has been implemented. [The example](http://surveyjs.org/examples/survey-startwithnewline.html)
