### ISSUE TITLE
Trigger designer has a typo "noncontains" --> "notcontains"

### ISSUE THREAD

**Issue by mattes3** [andrewtelnov/surveyjs#55]
The text in the trigger designer should be "notcontains":

![screen shot 2016-08-23 at 14 28 04](https://cloud.githubusercontent.com/assets/2496674/17891727/e90a0d66-693d-11e6-8c56-059a92da0a98.png)

**Comment by andrewtelnov** [comment]
Could catch!
Thank you,
Andrew
