### ISSUE TITLE
Separate CSS classes for next, prev and complete buttons

### ISSUE THREAD

**Issue by mattes3** [andrewtelnov/surveyjs#59]
At the moment, the CSS class of all navigation buttons is equal. Would be really good if the next, prev and complete buttons could have different classes (e.g. "next" and "complete" in green, "prev" in grey).

**Comment by andrewtelnov** [comment]
default css object has new attributes: navigation: { complete: "", prev: "", next: "" }. Use it to change the style of navigation buttons separately.

PS: To use this feature now, you should build the library from the source.

Thank you,
Andrew

**Comment by mattes3** [comment]
Cool, thanks!

Von einem mobilen Gerät gesendet - bitte entschuldigen Sie eventuelle Tippfehler.
