### ISSUE TITLE
matrixdropdown does not keep values selected

### ISSUE THREAD

**Issue by Teqa** [andrewtelnov/surveyjs#6]
The typical example matrixdropdown has a few rows and columns. 
Each has a select box with the same choices. 
Now when one of the selectboxes is changed, all the selectboxes change to the same value. 
Second issue: none of these values are kept so none of these can be stored. 

Expected result: being able to set a different selection for each select box.

**Comment by andrewtelnov** [comment]
Hello,
I am afraid that I do not get you. I have created an example of using the question: http://surveyjs.org/examples/questiontype-matrixdropdown.html
Could you please, check it out? It seems work as expected.
PS: I have fixed several bugs in QuestionMatrixdropdown yesterday.

Thank you,
Andrew

**Comment by Teqa** [comment]
Hi Andrew, 

Your example is very nice and helpful. 
This also makes me realise the issue is in the visual editor. 
In JSON you have supplied choices per column. 
In editor one can only set choices on question level, not column level. 
This is causing the question type to do the behaviour as described in this issue.

**Comment by andrewtelnov** [comment]
I have added a property editor for the MatrixDropdown.columns property.
