### ISSUE TITLE
Validation for non-required fields not possible

### ISSUE THREAD

**Issue by mattes3** [andrewtelnov/surveyjs#61]
When I switch on the number validator for a non-required textfield question, it suddenly forces the user to enter a number although the question is marked as "required=false".

As a user, I expect that I can leave the field empty or that I must enter a number.

**Comment by andrewtelnov** [comment]
Yes, indeed. The behavior was not correct. I have added a Unit Test for this scenario and fix the bug.

Thank you,
Andrew
