### ISSUE TITLE
Uncaught Error: ko.applyBindings

### ISSUE THREAD

**Issue by Xcellion** [andrewtelnov/surveyjs#63]
knockout-min.js:69 Uncaught Error: ko.applyBindings: first parameter should be your view model; second parameter should be a DOM node

Getting this error when trying to implement the main page example (http://surveyjs.org/index.html)

Not sure what's going on, can someone help please?

**Comment by andrewtelnov** [comment]
Hi,
Could you share your code? it is hard to say, why do you get the error.

Thank you,
Andrew

**Comment by Xcellion** [comment]
All I did was copy and paste the steps on the main page--
http://surveyjs.org/

Below is the HTML.

<head>
    <script src="
https://cdnjs.cloudflare.com/ajax/libs/knockout/3.3.0/knockout-min.js
"></script>
    <link href="css/survey.css" type="text/css" rel="stylesheet" />
    <script src="js/survey.min.js"></script>
    <script>
    var surveyJSON = { title: "Tell us, what technologies do you use?",
pages: [
        { name:"page1", questions: [
          { type: "radiogroup", choices: [ "Yes", "No" ], isRequired: true,
name: "frameworkUsing",title: "Do you use any front-end framework like
Bootstrap?" },
          { type: "checkbox", choices: ["Bootstrap","Foundation"],
hasOther: true, isRequired: true, name: "framework", title: "What front-end
framework do you use?", visible: false }
        ]},
        { name: "page2", questions: [
        { type: "radiogroup", choices: ["Yes","No"],isRequired: true, name:
"mvvmUsing", title: "Do you use any MVVM framework?" },
        { type: "checkbox", choices: [ "AngularJS", "KnockoutJS", "React"
], hasOther: true, isRequired: true, name: "mvvm", title: "What MVVM
framework do you use?", visible: false } ] },
        { name: "page3",questions: [
        { type: "comment", name: "about", title: "Please tell us about your
main requirements for Survey library" } ] }
        ],
        triggers: [
        { type: "visible", operator: "equal", value: "Yes", name:
"frameworkUsing", questions: ["framework"]},
        { type: "visible", operator: "equal", value: "Yes", name:
"mvvmUsing", questions: ["mvvm"]}
        ]
    }
    var survey = new Survey.Survey(surveyJSON, "surveyContainer");
    //Use onComplete event to save the data
    survey.onComplete.add(function(e){
        alert(e);
    });
    </script>
</head>

<body>
    <div id="surveyContainer"></div>
</body>

--

This is the error I am seeing in console. Perhaps something wrong with
Knockout?

[image: Inline image 1]


Wonmin Lee
won2blee@gmail.com <won2blee@brown.edu> | 718-309-7773 | www.1minlee.com

**Comment by andrewtelnov** [comment]
Hi,
Please move your script from the header section into the body section after "surveyContainer" div.
surveyjs could not find the "surveyContainer" since the the script is executing before surverContainer is rendered(created) by browser. The error tells that the surveyContainer doesn't exist yet.

**Comment by Xcellion** [comment]
thank you!
