### ISSUE TITLE
progress Bar and multiple triggers

### ISSUE THREAD

**Issue by rsands2801** [andrewtelnov/surveyjs#66]
There is a calculation issue with multiple triggers activiating a page to be visible.

**Two triggers:**

- If Q1 equals No show page 5
- If Q2 equals No show page 5

**The Problem**

Q1 (page 1) answer as no
-> Works fine and counter of progress bar to increments by 1

If we go to page 2 and answer Q2 as Yes
->counter decreases back down by 1

In either case it still shows page 5 and trigger works but the progress bar count is wrong.

**Comment by andrewtelnov** [comment]
Hi,
If it is not urgent, I will take a look after I  finish with: https://github.com/andrewtelnov/surveyjs/issues/65
If it is a showstopper for you, please let me know.

Thank you,
Andrew

**Comment by rsands2801** [comment]
@andrewtelnov Would be great to have it fixed next week but no rush.  Cool system, really nice work!

**Comment by andrewtelnov** [comment]
@rsands2801 
Ok, I have created an example: http://surveyjs.org/builder/?surveyid=3ae6c617-5d05-4b0f-9138-e7a997251653
It works as expected. The only thing, that it doesn't work:
1) answer 'No' on the first page, press Next (5 pages)
2) answer 'Yes' on the second page, press Next (4 pages)
3) Click Previous two times and come back to the first page
4) Click Next button and there are still 4 pages. Am I correct?

The problem that trigger works/runs only when the question value is actually changed. 
I am working on conditions (for questions and pages): https://github.com/andrewtelnov/surveyjs/issues/60
I hope to finish with run-time implementation on this week. After that I will work on editor.
As I understand, unless I am mistaken, you need this new feature.

Thank you,
Andrew

**Comment by rsands2801** [comment]
@andrewtelnov 

At 2) it is incorrect, it should be 5pages as the trigger for Q1 was met.  What the system is doing is analysing only by the question just answered, it should take a full view of triggers i.e. if Q1 trigger means page5 will show then the counter should show 5 at all steps.  What it is doing is saying Q2 trigger was false - and then thinking it should not show the page 5 in the progress bar count.   It does show page 5 fine but the counter at 2) is wrong.

**Comment by andrewtelnov** [comment]
@rsands2801 
Currently surveyjs has this behavior. I am afraid that some people has already used it in this way, so it would be a bad decision to change it :-(
However, I am in the middle of coding the multiple condition feature.
The page and question will have an attribute: visibleIf: string.
In your case, you will be able to set it as: page5.visibleIf = "q1 = 'No' or q2 = 'No'";  So, the page5 becomes visible if question q1 or question q2 has the value set to 'No', otherwise it is invisible.
I will come back as soon as I commit this feature into the repo. It will be cool, if you be able to build the library from the source (see the instruction in the repo readme file) and try the new feature in you survey.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@rsands2801 
I have added the required functionality. You may build the library from sources and give a try.
For the example I have posted above, you have to remove triggers and add visibleIf attribute to your page, like: `visibleIf: "'q1'='No' or 'q2'='No'"`
Please let me know how it works.

Thank you,
Andrew

**Comment by rsands2801** [comment]
@andrewtelnov 
I will try build from source and let you know.  When will it be pushed into the repo build?

**Comment by rsands2801** [comment]
@andrewtelnov 
is it possible to have the progress bar as a percentage that always shows the full question count and if a trigger means a question is skipped or not shown then the progress percentage just jumps along? i.e. it wouldn't change the overall percentage, just change the progress percent

**Comment by rsands2801** [comment]
@andrewtelnov 

Did a build but doesnt work if the condition is a string with spaces.  so "No it did not" would not work but "No" would

**Comment by andrewtelnov** [comment]
@rsands2801 Yes, thank you for reporting the bug. It was fixed and unit test is added.

**Comment by andrewtelnov** [comment]
@rsands2801 Could you please tell me more about the progress bar text? Probably with an example of the text.
PS: It will be cool if you start a new thread. It seems it is an enhancement which others may use as well.

Thank you,
Andrew

**Comment by rsands2801** [comment]
@andrewtelnov latest build worked great

**Comment by andrewtelnov** [comment]
@rsands2801, Please take into account, that I have started to use {youquestionName} for question names in expressions. 

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
New version is officially released.
