### ISSUE TITLE
Fill choices for dropdown, radio and checkox questions from a restfull service

### ISSUE THREAD

**Issue by andrewtelnov** [andrewtelnov/surveyjs#67]
A new choicesByUrl attribute/object has been added into dropdown, radio and checkox questions.
It has attributes:
url : string - the restfull service web url
path: string - the path the data from returning json. For example, for [this service](http://services.groupkt.com/country/get/all), the path will be: "RestResponse;result".
valueName: string - the name of the value in the json array. If it is empty, the first attribute is used.
valueTitle: string - the name of the title in the json array. If it is empty, the title equals to value.
Here is the example of filling dropdown question with the country list:
`{ type:"dropdown", name: "country", choicesByUrl: {url: 'http://services.groupkt.com/country/get/all', path: 'RestResponse;result', valueName: 'name'} }`

**Comment by andrewtelnov** [comment]
Could any one comment on this functionality? 
I have an idea to add parameters. For example, a user select a department, and then the list of employees in the department, using restful service. It will be an ability to use the {department} parameter, bound to the 'department' question value, in url for getting employee list via a restful service.
I am not sure that I am going into the right direction. Does somebody need it?

Thank you,
Andrew

**Comment by aslanbeily** [comment]
Hello Andrew,

Is there any reason why this doesn't work if you use capital letters in question names? just change pnl_region in both places to Pnl+region and whoops - nothing works :(
