### ISSUE TITLE
Ensure an answer provided for all rows of Matrix 

### ISSUE THREAD

**Issue by nanograv-pire** [andrewtelnov/surveyjs#69]
Currently making a Matrix question required only requires that you make a selection in one of the rows.  It seems that the "answercount" validator should work if the minCount is set to the number of rows in the matrix but it doesn't seem to.

**Comment by andrewtelnov** [comment]
Added a new property minRowCount: number int dynamic Matrix, the default value is 0.
Please use this property.

Thank you,
Andrew

**Comment by nanograv-pire** [comment]
This works for dynamicMatrix but not plain matrix.  I'm trying to adapt your code to the regular Matrix question class. Thanks!

**Comment by frankwo1** [comment]
Hi Andrew, I'm trying customize the validation message but can't seem to get it to work - can you help?
Frank

**Comment by frankwo1** [comment]
Hi Andrew,
1. I can't get the matrixdynamic answercount validation to work correctly - it only works when I increase the  "minRowCount": 5 (BUT IT SHOULD BE 4 ITEMS only)

**Comment by andrewtelnov** [comment]
@nategarver-daniels I have played with minRowCount and maxRowCount properties. They work as expected. Here is [the example](https://plnkr.co/edit/naziZwrowlXmaLt16Jm1?p=preview)
minRowCount keep the minimum row to this value and do not allow to remove any row if the number of rows equals to minRowCount. 

Thank you,
Andrew

**Comment by frankwo1** [comment]
I see, is it possible to have both error messages show? ( can I add a custom message - "you need to answer the top 5 questions (rows) "
 
<img width="469" alt="screen shot 2018-08-27 at 8 35 11 am" src="https://user-images.githubusercontent.com/19366310/44660068-71ab1b00-a9d4-11e8-8223-c54ae4332cc4.png">
Thanks
Frank

**Comment by andrewtelnov** [comment]
@frankwo1 You may use expression validator. Here is [the example](https://plnkr.co/edit/AhjQztqpGVGsmXYFbz18?p=preview).
However, why don't you want to set minRowCount to 5? In this case an end-user will not be able to fill less than 5 rows.

Thank you,
Andrew

**Comment by frankwo1** [comment]
Hi Andrew, Sorry to confuse you - I wanted to show you that the custom message DOES NOT show when the default message shows -->in this case "Please answer the question" 
See when I reverted it back to min 4/max 4 - I cannot get your custom message to show

https://plnkr.co/edit/yJNVktNYTT32aaIRKt9K?p=preview

How can I include a custom error message or replace default message?
Thanks
Frank

**Comment by frankwo1** [comment]
Thanks - that will work - for the future - how do I reference the values in the second column?

for example:
function surveyValidateQuestion(s, options) {
		if (options.name === 'using') {
				var question = s.getQuestionByName("using");
				if(!question.rows.every(function(row) { 
				  return (options.value || {})[row.itemValue] !== undefined; })) {
						options.error = "All rows should be answered.";
				}
		}
}

**Comment by andrewtelnov** [comment]
@frankwo1 This code should work:
```
if(!question.rows.every(function(row) {
  if(row.getQuestionByColumnName("yourColumnsName").isEmpty()) {
    options.error = "All rows should be answered.";
     return;
  }
}
```

Thank you,
Andrew

**Comment by frankwo1** [comment]
Thanks
