### ISSUE TITLE
Access via CDN

### ISSUE THREAD

**Issue by rap2hpoutre** [andrewtelnov/surveyjs#74]
Testing with codepen, jsfiddle, etc. may be easier with a CDN (Anyway, I opened a request here: https://github.com/cdnjs/cdnjs/issues/9101)

**Comment by andrewtelnov** [comment]
Yes, you are right. This is something as 'must be'. However, I think I will have to add the versioning into the javascript file names. so it is "survey-0.9.12.js". 

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
@rap2hpoutre @andrewtelnov , we can use https://unpkg.com  **Unpkg**  - is a fast, global content delivery network for stuff that is published to npm. 

Just try https://unpkg.com/survey-react or https://unpkg.com/survey-knockout

**Comment by rap2hpoutre** [comment]
👍
