### ISSUE TITLE
Uncaught exceptions occuring

### ISSUE THREAD

**Issue by mattes3** [andrewtelnov/surveyjs#78]
See https://justaskusers.herokuapp.com/quote/new

When you answer the questions on the first and second page, you get to a third page called "Schedule".

Go to the last question on that page. The question is called "Availability".

Open the browser inspector window and click on "Console".

Click on the "+" button to add a third row. Try to fill values into the cells like this:

![screen shot 2016-09-29 at 14 16 26](https://cloud.githubusercontent.com/assets/2496674/18953579/75b43b64-864f-11e6-9218-b2fec03ef836.png)

In the console window, you will get error messages like this:

![screen shot 2016-09-29 at 14 16 35](https://cloud.githubusercontent.com/assets/2496674/18953596/8fe7cd2a-864f-11e6-9759-302a98e77483.png)

What is happening here? When the survey completes, I find strange data in the table.

**Comment by andrewtelnov** [comment]
@mattes3 the course the error the following code:
```
<ul data-bind="foreach: studyTimeSlots()">
<li>On <span data-bind="text: date"></span> from <span data-bind="text: from"></span> to<span data-bind="text: to"></span> with max. 
<span data-bind="text: numberOfParticipants"></span> participants
</li>
<li>On <span data-bind="text: date">01/20</span> from <span data-bind="text: from"></span> to
<span data-bind="text: to"></span> with max. <span data-bind="text: numberOfParticipants"></span> participants
</li>
<li>On <span data-bind="text: date"></span> from <span data-bind="text: from"></span> to
                      <span data-bind="text: to"></span> with max. <span data-bind="text: numberOfParticipants"></span> participants
</li>
</ul>
```
If I remove this ul from the DOM, the error is gone. This code generated some how dynamically.

Do you need an event on adding new row, where you may initialized values? I guess you need this.

Thank you,
Andrew

**Comment by mattes3** [comment]
I am reacting to survey.onOptionValueChanged()

I get the entire array of values and I thought that the new row in the array was already initialized so that I can display it with a Knockout binding.

If this is not the case then: yes, I will need an initialization event.

**Comment by andrewtelnov** [comment]
Probably you may continue using this event. All you need to do is to make sure that all fields in the row are defined. So, set the fields with empty values. By default the row is empty: {}.
If it doesn't help, then I will think about another event, probably it will be on the question level.
Let me know about your progress.

**Comment by mattes3** [comment]
Problem solved. I changed my Knockout bindings so that they can deal with non-existent properties, like so:

```
<ul data-bind="foreach: { data: studyTimeSlots, as: 'slot' }">
  <li><span data-bind="text: slot.date || '' "></span></li>
</ul>
```

So, if the "date" property is not yet defined, the binding will return an empty string which makes Knockout happy.

**Comment by andrewtelnov** [comment]
I have not known about this possibility. I used to create a new observable for this.
Anyway, great that you have solved the issue.

Thank you,
Andrew
