### ISSUE TITLE
Could we have <button> instead of <input type="button"> ?

### ISSUE THREAD

**Issue by mattes3** [andrewtelnov/surveyjs#79]
I am using survey.js in an HTML5 context. Could I have real <button>s because they render better on an iPhone when using Material Design Lite CSS?

**Comment by andrewtelnov** [comment]
@mattes3 I am thinking about heavily rewrite knockout templates and react rendering.
Actually, I want to merge standard and bootstrap html (did some simple merging on previous week) and create the ability to support others css frameworks. Material Design is the first candidate.
I want to remove survey.bootstrap.js and have only survey.js file. There will be an property: survey.cssFramework: string ("standard", "bootstrap", "materials"). There should be an ability to add another one, or of course modify the current, as you can do now.

I can not promise, that I will be able to change input tag on button tag. I will need to experiment with this. If it works better on mobile and fine on desktop, then sure, I will do it.
I was going to start with this task in one-two weeks.

Thank you,
Andrew

**Comment by mattes3** [comment]
Cool, thanks, Andrew!

**Comment by andrewtelnov** [comment]
I have posted the updated knockout version: https://github.com/andrewtelnov/surveyjs/issues/86
