### ISSUE TITLE
Make sure all fields in a matrix questions are selected

### ISSUE THREAD

**Issue by piscis** [andrewtelnov/surveyjs#94]
Hi Andrew, 

I have a question regarding the matrix question component. 
Is it possible to use a validator to require at least one selected value per row?

I tried the following with no success:
https://gist.github.com/piscis/dd6293811300a0fd46abea3cda41d179

Thanks,

Alex

**Comment by andrewtelnov** [comment]
@piscis Unfortunately, there is no way to do it right now for the current version.
I will add isAllRowRequired property (default is false) into upcoming version. We will release it on this week.

Thank you,
Andrew

**Comment by piscis** [comment]
Hi Andrew, 

thank you for the quick reply. I'm really looking forward to it!

All the Best,

Alex

**Comment by andrewtelnov** [comment]
It is included into v0.10.0

**Comment by piscis** [comment]
I tested this with the following question matrix:

https://gist.github.com/piscis/8833d4ba774953532db5d94d36c034c6

but somehow its not picking up the `isAllRowRequired` attribute.

I tried to rebuild the latest master but no luck

**Comment by piscis** [comment]
Using React: It looks like that setting `isAllRowRequired` on a `ReactSurveyModel` will not be propagated to the `QuestionMatrixModel` but I couldn't figure whats wrong.

**Comment by andrewtelnov** [comment]
Yes, sorry about that. I forgot to include the property into json serialization. It is done now. I have updated the [example](http://surveyjs.org/examplesreact/questiontype-matrix.html). I have added a checkbox to turn on/off this property.

Thank you,
Andrew
